import {
  Activity,
  BookOpen,
  Car,
  Check,
  CheckCircle,
  CircleDot,
  Clock,
  CloudRain,
  Flag,
  Frown,
  Gamepad2,
  Gauge,
  Hand,
  HelpCircle,
  Home,
  LifeBuoy,
  MessageCircle,
  Move,
  Music,
  Octagon,
  PartyPopper,
  PauseCircle,
  Pencil,
  Plus,
  Repeat,
  Sailboat,
  Shield,
  Sparkles,
  Square,
  ThumbsDown,
  Trophy,
  User,
  Users,
  Volume2,
  Waves,
  Wind,
  X,
  XCircle,
  type LucideProps,
} from "lucide-react";
import type { ComponentType } from "react";

const ICONS: Record<string, ComponentType<LucideProps>> = {
  "help-circle": HelpCircle,
  "life-buoy": LifeBuoy,
  help: HelpCircle,
  plus: Plus,
  "x-circle": XCircle,
  x: X,
  user: User,
  users: Users,
  "pause-circle": PauseCircle,
  pause: PauseCircle,
  frown: Frown,
  "cloud-rain": CloudRain,
  "check-circle": CheckCircle,
  check: Check,
  hand: Hand,
  octagon: Octagon,
  stop: Octagon,
  move: Move,
  "thumbs-down": ThumbsDown,
  car: Car,
  sailboat: Sailboat,
  boat: Sailboat,
  flag: Flag,
  "book-open": BookOpen,
  book: BookOpen,
  pencil: Pencil,
  music: Music,
  wind: Wind,
  "circle-dot": CircleDot,
  repeat: Repeat,
  clock: Clock,
  shield: Shield,
  activity: Activity,
  square: Square,
  gauge: Gauge,
  waves: Waves,
  home: Home,
  "gamepad-2": Gamepad2,
  "message-circle": MessageCircle,
  "party-popper": PartyPopper,
  "volume-2": Volume2,
  trophy: Trophy,
  sparkles: Sparkles,
};

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Component = ICONS[name] ?? Sparkles;
  return <Component {...props} />;
}
